### ISSUE TITLE
missing packages from requirements (setup.py)

### ISSUE THREAD

**Issue by ferrigno** [cdcihub/oda-kb#2]
I made a fresh virtual environment for other reasons

`````virtualenv testKB`
`source testKB/bin/activate`
`pip install oda-knowledge-base
python -m odakb
``

It turns out that  **you miss rdflib, cwltool, and requests from requirements**.

**Comment by volodymyrss** [comment]
please have a look on the available package extras and reopen if you do not manage to use them.
